#pragma once
#define SIZE_MULTIPLIER 8
#define REAL_WIDTH 160
#define REAL_HEIGHT 128
#define MAP_WIDTH REAL_WIDTH / SIZE_MULTIPLIER
#define MAP_HEIGHT REAL_HEIGHT / SIZE_MULTIPLIER
#define STARTER_PLAYER_POSITION_X 3
#define STARTER_PLAYER_POSITION_Y 3
#define MINIMAL_JOYSTICK_DEVIATION_TO_MOVE 300
#define JOYSTICK_READ_MINIMAL_COOLDOWN 100
#define LEVEL_COUNT 2
#define MAX_GAME_OBJECTS_PER_LEVEL 50
#define PLAYER_SIZE_X 1
#define PLAYER_SIZE_Y 1
